version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: backstage-app
    user: node
    volumes:
      - ..:/workspace
      # # Use a named volume for the source code
      # - my-app:/workspace
      # # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - backstage

    depends_on:
      - db

    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

    networks:
      - backstage
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  # my-app:
  vscode-extensions:
  postgres-data:

networks:
  backstage: